### ISSUE TITLE
请问下如果是TCP连接根据自定义的协议上传的byte流，那么ThingsBoard支持对这种协议的定义和解码支持吗

### ISSUE THREAD

**Issue by kfd9** [IoT-Technology/IOT-Technical-Guide#1]
我最近开发的一个物联网应用，通过netty创建一个TCP端口应用，接收设备端上报的byte字节流，然后根据通信协议解码，像这种数据包ThingsBoard能支持协议的定义、解码、数据转换、存储吗？

**Comment by sanshengshui** [comment]
ThingsBoard是支持的，当然这种支持是那种需要自己开发代码的，对其进行二次开发！像你这种物联网应用，还是自己开发比较好👌，ThingsBoard主要为我们提供代码思路和架构思想

**Comment by AWangji** [comment]
你好我最近也在搞这个，楼主现在弄得怎么样了，我现在在修改messagetype类型的时候出了一点问题，可以交流一下吗
